// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: openapi/charge/common.proto

package charge

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodType int32

const (
	MethodType_GET  MethodType = 0
	MethodType_POST MethodType = 1
	MethodType_PUT  MethodType = 2
)

// Enum value maps for MethodType.
var (
	MethodType_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
	}
	MethodType_value = map[string]int32{
		"GET":  0,
		"POST": 1,
		"PUT":  2,
	}
)

func (x MethodType) Enum() *MethodType {
	p := new(MethodType)
	*p = x
	return p
}

func (x MethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_charge_common_proto_enumTypes[0].Descriptor()
}

func (MethodType) Type() protoreflect.EnumType {
	return &file_openapi_charge_common_proto_enumTypes[0]
}

func (x MethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodType.Descriptor instead.
func (MethodType) EnumDescriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{0}
}

type PassWayType int32

const (
	PassWayType_QUERY     PassWayType = 0 // Query Param
	PassWayType_PATH      PassWayType = 1 // Path Param
	PassWayType_BODY      PassWayType = 2 // Request Body(json)
	PassWayType_MULTIPART PassWayType = 3 // Multipart/form-data
)

// Enum value maps for PassWayType.
var (
	PassWayType_name = map[int32]string{
		0: "QUERY",
		1: "PATH",
		2: "BODY",
		3: "MULTIPART",
	}
	PassWayType_value = map[string]int32{
		"QUERY":     0,
		"PATH":      1,
		"BODY":      2,
		"MULTIPART": 3,
	}
)

func (x PassWayType) Enum() *PassWayType {
	p := new(PassWayType)
	*p = x
	return p
}

func (x PassWayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PassWayType) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_charge_common_proto_enumTypes[1].Descriptor()
}

func (PassWayType) Type() protoreflect.EnumType {
	return &file_openapi_charge_common_proto_enumTypes[1]
}

func (x PassWayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PassWayType.Descriptor instead.
func (PassWayType) EnumDescriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{1}
}

type InterfaceStatus int32

const (
	InterfaceStatus_ABLE   InterfaceStatus = 0
	InterfaceStatus_UNABLE InterfaceStatus = 1
	InterfaceStatus_DELETE InterfaceStatus = 2
)

// Enum value maps for InterfaceStatus.
var (
	InterfaceStatus_name = map[int32]string{
		0: "ABLE",
		1: "UNABLE",
		2: "DELETE",
	}
	InterfaceStatus_value = map[string]int32{
		"ABLE":   0,
		"UNABLE": 1,
		"DELETE": 2,
	}
)

func (x InterfaceStatus) Enum() *InterfaceStatus {
	p := new(InterfaceStatus)
	*p = x
	return p
}

func (x InterfaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_charge_common_proto_enumTypes[2].Descriptor()
}

func (InterfaceStatus) Type() protoreflect.EnumType {
	return &file_openapi_charge_common_proto_enumTypes[2]
}

func (x InterfaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceStatus.Descriptor instead.
func (InterfaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{2}
}

type ChargeType int32

const (
	ChargeType_TIMES  ChargeType = 0 // 按次计费
	ChargeType_TOKENS ChargeType = 1 // 按量计费
)

// Enum value maps for ChargeType.
var (
	ChargeType_name = map[int32]string{
		0: "TIMES",
		1: "TOKENS",
	}
	ChargeType_value = map[string]int32{
		"TIMES":  0,
		"TOKENS": 1,
	}
)

func (x ChargeType) Enum() *ChargeType {
	p := new(ChargeType)
	*p = x
	return p
}

func (x ChargeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeType) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_charge_common_proto_enumTypes[3].Descriptor()
}

func (ChargeType) Type() protoreflect.EnumType {
	return &file_openapi_charge_common_proto_enumTypes[3]
}

func (x ChargeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeType.Descriptor instead.
func (ChargeType) EnumDescriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{3}
}

type LogStatus int32

const (
	LogStatus_SUCCESS           LogStatus = 0 // 成功
	LogStatus_UNKNOWN_FAIL      LogStatus = 1 // 未知错误
	LogStatus_NETWORK_FAIL      LogStatus = 2 // 网络错误
	LogStatus_INVALID_PARAMS    LogStatus = 3 // 参数错误
	LogStatus_PERMISSION_DENIED LogStatus = 4 // 没有对应权限
)

// Enum value maps for LogStatus.
var (
	LogStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_FAIL",
		2: "NETWORK_FAIL",
		3: "INVALID_PARAMS",
		4: "PERMISSION_DENIED",
	}
	LogStatus_value = map[string]int32{
		"SUCCESS":           0,
		"UNKNOWN_FAIL":      1,
		"NETWORK_FAIL":      2,
		"INVALID_PARAMS":    3,
		"PERMISSION_DENIED": 4,
	}
)

func (x LogStatus) Enum() *LogStatus {
	p := new(LogStatus)
	*p = x
	return p
}

func (x LogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_charge_common_proto_enumTypes[4].Descriptor()
}

func (LogStatus) Type() protoreflect.EnumType {
	return &file_openapi_charge_common_proto_enumTypes[4]
}

func (x LogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStatus.Descriptor instead.
func (LogStatus) EnumDescriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{4}
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BaseInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 接口名
	Host       string          `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                        // 域名
	Path       string          `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                        // 调用路径
	Method     MethodType      `protobuf:"varint,5,opt,name=method,proto3,enum=openapi.charge.MethodType" json:"method,omitempty"`    // 调用方式
	PassWay    PassWayType     `protobuf:"varint,6,opt,name=passWay,proto3,enum=openapi.charge.PassWayType" json:"passWay,omitempty"` // 传值方式
	Params     []*Parameter    `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`                                    // 参数列表
	Content    string          `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Status     InterfaceStatus `protobuf:"varint,9,opt,name=status,proto3,enum=openapi.charge.InterfaceStatus" json:"status,omitempty"` // 接口状态
	CreateTime int64           `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime int64           `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *BaseInterface) Reset() {
	*x = BaseInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInterface) ProtoMessage() {}

func (x *BaseInterface) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInterface.ProtoReflect.Descriptor instead.
func (*BaseInterface) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInterface) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseInterface) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BaseInterface) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BaseInterface) GetMethod() MethodType {
	if x != nil {
		return x.Method
	}
	return MethodType_GET
}

func (x *BaseInterface) GetPassWay() PassWayType {
	if x != nil {
		return x.PassWay
	}
	return PassWayType_QUERY
}

func (x *BaseInterface) GetParams() []*Parameter {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BaseInterface) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BaseInterface) GetStatus() InterfaceStatus {
	if x != nil {
		return x.Status
	}
	return InterfaceStatus_ABLE
}

func (x *BaseInterface) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *BaseInterface) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type FullInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInterfaceId string          `protobuf:"bytes,2,opt,name=baseInterfaceId,proto3" json:"baseInterfaceId,omitempty"`                       // 基础接口id
	UserId          string          `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`                                         // 面向用户id
	ChargeType      ChargeType      `protobuf:"varint,4,opt,name=chargeType,proto3,enum=openapi.charge.ChargeType" json:"chargeType,omitempty"` // 收费模式
	Price           int64           `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`                                          // 接口单价
	Status          InterfaceStatus `protobuf:"varint,7,opt,name=status,proto3,enum=openapi.charge.InterfaceStatus" json:"status,omitempty"`    // 接口状态
	CreateTime      int64           `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`                                // 创建时间
	UpdateTime      int64           `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`                                // 更新时间
}

func (x *FullInterface) Reset() {
	*x = FullInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullInterface) ProtoMessage() {}

func (x *FullInterface) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullInterface.ProtoReflect.Descriptor instead.
func (*FullInterface) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{2}
}

func (x *FullInterface) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FullInterface) GetBaseInterfaceId() string {
	if x != nil {
		return x.BaseInterfaceId
	}
	return ""
}

func (x *FullInterface) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FullInterface) GetChargeType() ChargeType {
	if x != nil {
		return x.ChargeType
	}
	return ChargeType_TIMES
}

func (x *FullInterface) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FullInterface) GetStatus() InterfaceStatus {
	if x != nil {
		return x.Status
	}
	return InterfaceStatus_ABLE
}

func (x *FullInterface) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FullInterface) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type Margin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FullInterfaceId string `protobuf:"bytes,3,opt,name=fullInterfaceId,proto3" json:"fullInterfaceId,omitempty"`
	Margin          int64  `protobuf:"varint,4,opt,name=margin,proto3" json:"margin,omitempty"`
	CreateTime      int64  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime      int64  `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *Margin) Reset() {
	*x = Margin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Margin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Margin) ProtoMessage() {}

func (x *Margin) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Margin.ProtoReflect.Descriptor instead.
func (*Margin) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{3}
}

func (x *Margin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Margin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Margin) GetFullInterfaceId() string {
	if x != nil {
		return x.FullInterfaceId
	}
	return ""
}

func (x *Margin) GetMargin() int64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *Margin) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Margin) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type Discount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Rate int64 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Low  int64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *Discount) Reset() {
	*x = Discount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discount) ProtoMessage() {}

func (x *Discount) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discount.ProtoReflect.Descriptor instead.
func (*Discount) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{4}
}

func (x *Discount) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Discount) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Discount) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

type Gradient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseInterfaceId string          `protobuf:"bytes,2,opt,name=baseInterfaceId,proto3" json:"baseInterfaceId,omitempty"`
	Discounts       []*Discount     `protobuf:"bytes,3,rep,name=discounts,proto3" json:"discounts,omitempty"`
	Status          InterfaceStatus `protobuf:"varint,4,opt,name=status,proto3,enum=openapi.charge.InterfaceStatus" json:"status,omitempty"`
	CreateTime      int64           `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime      int64           `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *Gradient) Reset() {
	*x = Gradient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gradient) ProtoMessage() {}

func (x *Gradient) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gradient.ProtoReflect.Descriptor instead.
func (*Gradient) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{5}
}

func (x *Gradient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gradient) GetBaseInterfaceId() string {
	if x != nil {
		return x.BaseInterfaceId
	}
	return ""
}

func (x *Gradient) GetDiscounts() []*Discount {
	if x != nil {
		return x.Discounts
	}
	return nil
}

func (x *Gradient) GetStatus() InterfaceStatus {
	if x != nil {
		return x.Status
	}
	return InterfaceStatus_ABLE
}

func (x *Gradient) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Gradient) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 记录id
	FullInterfaceId string    `protobuf:"bytes,2,opt,name=fullInterfaceId,proto3" json:"fullInterfaceId,omitempty"`              // 被调用的完整接口id
	UserId          string    `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`                                // 调用用户的id
	KeyId           string    `protobuf:"bytes,4,opt,name=keyId,proto3" json:"keyId,omitempty"`                                  // 调用key的id
	Status          LogStatus `protobuf:"varint,5,opt,name=status,proto3,enum=openapi.charge.LogStatus" json:"status,omitempty"` // 调用的状态
	Info            string    `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`                                    // 调用相关信息
	Count           int64     `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`                                 // 数量(按次则是次数1，按token则是token数)
	Value           int64     `protobuf:"varint,8,opt,name=value,proto3" json:"value,omitempty"`                                 // 调用扣费
	Timestamp       int64     `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                         // 调用时间
	CreateTime      int64     `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"`                      // 创建时间
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetFullInterfaceId() string {
	if x != nil {
		return x.FullInterfaceId
	}
	return ""
}

func (x *Log) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Log) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Log) GetStatus() LogStatus {
	if x != nil {
		return x.Status
	}
	return LogStatus_SUCCESS
}

func (x *Log) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Log) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Log) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Log) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TxId       string `protobuf:"bytes,2,opt,name=txId,proto3" json:"txId,omitempty"`
	Increment  int64  `protobuf:"varint,3,opt,name=increment,proto3" json:"increment,omitempty"`
	MarginId   string `protobuf:"bytes,4,opt,name=marginId,proto3" json:"marginId,omitempty"`
	CreateTime int64  `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openapi_charge_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_charge_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_openapi_charge_common_proto_rawDescGZIP(), []int{7}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Account) GetIncrement() int64 {
	if x != nil {
		return x.Increment
	}
	return 0
}

func (x *Account) GetMarginId() string {
	if x != nil {
		return x.MarginId
	}
	return ""
}

func (x *Account) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_openapi_charge_common_proto protoreflect.FileDescriptor

var file_openapi_charge_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x22, 0x33, 0x0a,
	0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x8c, 0x03, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x32, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x35, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x57, 0x61, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x57, 0x61, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x70, 0x61, 0x73, 0x73, 0x57, 0x61, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xac, 0x02, 0x0a, 0x0d, 0x46, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xb2, 0x01, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x75,
	0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x22, 0xf5, 0x01, 0x0a, 0x08, 0x47, 0x72,
	0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x36, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x09, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x9e, 0x02, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x75, 0x6c,
	0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x66, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6b,
	0x65, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49,
	0x64, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x28, 0x0a, 0x0a,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x55, 0x54, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x0b, 0x50, 0x61, 0x73, 0x73, 0x57, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x54, 0x48, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f,
	0x44, 0x59, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50, 0x41, 0x52,
	0x54, 0x10, 0x03, 0x2a, 0x33, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x23, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x53, 0x10, 0x01, 0x2a, 0x67, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x54,
	0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45,
	0x4e, 0x49, 0x45, 0x44, 0x10, 0x04, 0x42, 0x77, 0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x68,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x69, 0x64, 0x6c, 0x67, 0x65, 0x6e, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x42, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x41, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61,
	0x72, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x69, 0x64, 0x6c, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_openapi_charge_common_proto_rawDescOnce sync.Once
	file_openapi_charge_common_proto_rawDescData = file_openapi_charge_common_proto_rawDesc
)

func file_openapi_charge_common_proto_rawDescGZIP() []byte {
	file_openapi_charge_common_proto_rawDescOnce.Do(func() {
		file_openapi_charge_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_openapi_charge_common_proto_rawDescData)
	})
	return file_openapi_charge_common_proto_rawDescData
}

var file_openapi_charge_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openapi_charge_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_openapi_charge_common_proto_goTypes = []interface{}{
	(MethodType)(0),       // 0: openapi.charge.MethodType
	(PassWayType)(0),      // 1: openapi.charge.PassWayType
	(InterfaceStatus)(0),  // 2: openapi.charge.InterfaceStatus
	(ChargeType)(0),       // 3: openapi.charge.ChargeType
	(LogStatus)(0),        // 4: openapi.charge.LogStatus
	(*Parameter)(nil),     // 5: openapi.charge.Parameter
	(*BaseInterface)(nil), // 6: openapi.charge.BaseInterface
	(*FullInterface)(nil), // 7: openapi.charge.FullInterface
	(*Margin)(nil),        // 8: openapi.charge.Margin
	(*Discount)(nil),      // 9: openapi.charge.Discount
	(*Gradient)(nil),      // 10: openapi.charge.Gradient
	(*Log)(nil),           // 11: openapi.charge.Log
	(*Account)(nil),       // 12: openapi.charge.Account
}
var file_openapi_charge_common_proto_depIdxs = []int32{
	0, // 0: openapi.charge.BaseInterface.method:type_name -> openapi.charge.MethodType
	1, // 1: openapi.charge.BaseInterface.passWay:type_name -> openapi.charge.PassWayType
	5, // 2: openapi.charge.BaseInterface.params:type_name -> openapi.charge.Parameter
	2, // 3: openapi.charge.BaseInterface.status:type_name -> openapi.charge.InterfaceStatus
	3, // 4: openapi.charge.FullInterface.chargeType:type_name -> openapi.charge.ChargeType
	2, // 5: openapi.charge.FullInterface.status:type_name -> openapi.charge.InterfaceStatus
	9, // 6: openapi.charge.Gradient.discounts:type_name -> openapi.charge.Discount
	2, // 7: openapi.charge.Gradient.status:type_name -> openapi.charge.InterfaceStatus
	4, // 8: openapi.charge.Log.status:type_name -> openapi.charge.LogStatus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_openapi_charge_common_proto_init() }
func file_openapi_charge_common_proto_init() {
	if File_openapi_charge_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_openapi_charge_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Margin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Discount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gradient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openapi_charge_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_openapi_charge_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openapi_charge_common_proto_goTypes,
		DependencyIndexes: file_openapi_charge_common_proto_depIdxs,
		EnumInfos:         file_openapi_charge_common_proto_enumTypes,
		MessageInfos:      file_openapi_charge_common_proto_msgTypes,
	}.Build()
	File_openapi_charge_common_proto = out.File
	file_openapi_charge_common_proto_rawDesc = nil
	file_openapi_charge_common_proto_goTypes = nil
	file_openapi_charge_common_proto_depIdxs = nil
}

var _ context.Context
